# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89e5654fbbd19946cce4516d55b642a60ba269cee3e87a8830a45215000edf406399f95e389836127b1c08e8337d79c0d960451a1b6c1902191c225f90edb3f8

test:
  secret_key_base: c50201eb7a8adf71f4ab5adb7a11d92ff45b14df81fad71bb1074e061cdfd1fae2084b4b4c37efa0c10354bd8dc93a9ce71c2474b965d1bfe3370213636e2ea9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
